### ISSUE TITLE
add axi lite monitoring of DSP specific components

### ISSUE THREAD

**Issue by sioan** [slaclab/lcls2-pcie-apps#31]
The peak finder, pre-scaler,  IIR filter, null filter, and subtractor need axi lite monitoring of frame counts, and other meta data as implemented in standard TID-AIR modules such as the axi-stream batcher event builder.  

This will be important for future debugging.

**Comment by ruck314** [comment]
Using JIRA to track issue:
https://jira.slac.stanford.edu/browse/ESCLINK-16
