### ISSUE TITLE
pre-scaler doesn't handle single frame transfers

### ISSUE THREAD

**Issue by sioan** [slaclab/lcls2-pcie-apps#32]
the pre-scaler does not pre-scale frames that are one transfer wide.  Pre-scaled frames that are one transfer wide have no null filter nor frame sent.  This is because the pre-scaler gets stuck in the blow off state.

The exception to this is single null frames sent from another daisy chained prescaler. A cludge, that re-purposes the side band data needed for the axi-stream batcher event builder to process null frames, is used to break out of the pre-scalers blowoff state.

**Comment by ruck314** [comment]
Using JIRA to track issues:
https://jira.slac.stanford.edu/browse/ESCLINK-15
