### ISSUE TITLE
TimeToolCore bypass causes firmware hang

### ISSUE THREAD

**Issue by sioan** [slaclab/lcls2-pcie-apps#33]
Bypassing the entire time tool core causes a hang.  This started when the FEX placeholder was replaced with the intended FEX processing.

The hang recovers when the bypass is de-asserted. 

Also, several full frames are processed before the hang occurs indicating that this might be due to a filling FIFO.

the bypass in this issue not referring to the axistreameventbuilder bypass, but rather the TimeToolCore bypass module.  Adding axi lite monitoring would facilitate debugging this issue.

**Comment by ruck314** [comment]
Using JIRA to track issues:
https://jira.slac.stanford.edu/browse/ESCLINK-14
